schema: https://nitrogen-token-tracker.molecula.tech/graphql
documents: '**/*.graphql'

extensions:
  endpoints:
    default:
      url: https://nitrogen-token-tracker.molecula.tech/graphql
      subscriptions: wss://nitrogen-token-tracker.molecula.tech/graphql
